url: "" # here is your discord webhook
#content: ""
#username: ""
#avatar_url: ""
#tts: false
embeds: # Placeholders: %player%, %group%, %casetype%, %animation%, %casetitle%.
  title: "DonateCase, opening case:"
#  description: ""
  color: 444444
  footer:
    text: "DCWebHook | Addon for DonateCase"
    icon_url: "https://www.spigotmc.org/data/resource_icons/106/106701.jpg?1678739430"
#  author:
#    name: ""
#    url: ""
#    icon_url: ""
  fields:
    - name: ""
      value: "**Player:** %player%"
      inline: false
    - name: ""
      value: "**Type:** %casetype%"
      inline: false
    - name: ""
      value: "**Prize:** %group%"
      inline: false
